### ISSUE TITLE
Exception in RTMA asyncio download script

### ISSUE THREAD

**Issue by tombrauer** [HydrologicEngineeringCenter/data-retrieval-scripts#5]
@danhamill the asyncio scripts are great! So much speed!

I hit an exception running the asyncio script for RTMA Temperature. I ran for the dates 2016-10-01 00:00 to 2016-10-15 00:00. It's very likely there could be a missing grid in there causing the crash. Can you try reproducing, and see if there is a workaround that doesn't bring the script down? For reference, we added some missing URL logic in https://github.com/HydrologicEngineeringCenter/data-retrieval-scripts/blob/master/retrieve_qpe_gagecorr_01h.py

```Traceback (most recent call last):
  File "C:/Projects/data-retrieval-scripts/RTMA_Temp_async_download.py", line 63, in <module>
    results = loop.run_until_complete(main())
  File "C:\Projects\data-retrieval-scripts\venv\lib\site-packages\nest_asyncio.py", line 95, in run_until_complete
    return f.result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1729.0_x64__qbz5n2kfra8p0\lib\asyncio\futures.py", line 178, in result
    raise self._exception
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1729.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 282, in __step
    result = coro.throw(exc)
  File "C:/Projects/data-retrieval-scripts/RTMA_Temp_async_download.py", line 57, in main
    return await asyncio.gather(*tasks)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1729.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 349, in __wakeup
    future.result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1729.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 282, in __step
    result = coro.throw(exc)
  File "C:/Projects/data-retrieval-scripts/RTMA_Temp_async_download.py", line 26, in download_coroutine
    chunk = await response.content.read(1024)
  File "C:\Projects\data-retrieval-scripts\venv\lib\site-packages\aiohttp\streams.py", line 368, in read
    await self._wait('read')
  File "C:\Projects\data-retrieval-scripts\venv\lib\site-packages\aiohttp\streams.py", line 296, in _wait
    await waiter
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1729.0_x64__qbz5n2kfra8p0\lib\asyncio\futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1729.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 349, in __wakeup
    future.result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1729.0_x64__qbz5n2kfra8p0\lib\asyncio\futures.py", line 178, in result
    raise self._exception
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
```

**Comment by danhamill** [comment]
I've had this problem too.  It has something to do with the Iowa Mesonet servers getting upset when too many threads are created.  A hack of a work around is to just feed `async main` with a small list of urls.  Something like:

```python
from datetime import datetime
from datetime import timedelta
import os
import nest_asyncio
nest_asyncio.apply()
import asyncio
import aiohttp
import async_timeout
import numpy as np

async def download_coroutine(url, session):
    with async_timeout.timeout(1200):
        async with session.get(url) as response:
            if response.status == 200:
                fp = r"C:\workspace\ririe\HMS\data\precip\2020" + os.sep + os.path.basename(url)
                with open(fp, 'wb') as f_handle:
                    while True:
                        chunk = await response.content.read(1024)
                        if not chunk:
                            break
                        f_handle.write(chunk)
            else:
                print(url)
            return await response.release()

async def main(loop, tmp):
       
    async with aiohttp.ClientSession() as session:
        tasks = [download_coroutine(url, session) for url in tmp]
        return await asyncio.gather(*tasks)




if __name__ == '__main__':
    
    start = datetime(2020, 5, 7, 0, 0)
    end = datetime(2020, 8, 1, 0, 0)
    hour = timedelta(hours=1)
    
    date = start
    urls = []
    opath = []
    while date < end:
        url = "http://mtarchive.geol.iastate.edu/{:04d}/{:02d}/{:02d}/mrms/ncep/GaugeCorr_QPE_01H/GaugeCorr_QPE_01H_00.00_{:04d}{:02d}{:02d}-{:02d}0000.grib2.gz".format(
        date.year, date.month, date.day, date.year, date.month, date.day, date.hour)
        #print(url)
        destination = r"C:\workspace\ririe\HMS\data\precip\2020"
        
        filename = url.split("/")[-1]
        if not os.path.isfile(destination + os.sep + filename):
            urls.append(url)
            opath.append(destination + os.sep + filename)
        date += hour

    chunk_size = 50
    chunked_urls = [urls[i * chunk_size:(i + 1) * chunk_size] for i in range((len(urls) + chunk_size - 1) // chunk_size )] 

    for tmp in chunked_urls:
        loop = asyncio.get_event_loop()        
        results = loop.run_until_complete(main(loop, tmp))
        del loop, results
```

I'm thinking about posting a bounty on SO to see if I can figure out how to complete the downloads with `aiohttp`, but this approach seems to work pretty well.  I just downloaded 2000+ qpe grids with out any connection issues.  

If I figure it out I'll submit a new PR.

**Comment by tombrauer** [comment]
Good to know. I'll give that a try!
